name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Docs
        run: doxygen doxygen.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html