name: C++ macOS Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
        
      - name: Show compiler version
        run: |
          sysctl -n machdep.cpu.brand_string
          clang++ --version

      - name: Clean project
        run: make clean || true

      - name: Build project
        run: make

      - name: Run tests
        run: make test