name: C++ Windows Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Show compiler version
        run: cl.exe

      - name: Clean project
        shell: powershell
        run: |
          if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
          if (Test-Path "bin") { Remove-Item -Recurse -Force "bin" }

      
      - name: Configure and Build
        shell: powershell
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run tests
        shell: powershell
        run: |
          cd build
          ctest -C Release --output-on-failure